# Number of days of inactivity before an issue becomes stale
daysUntilStale: 150
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
    - "Feature Request"
    - "Feature request from DASH IF IOP"
    - "Pri-Critical"
# Label to use when marking an issue as stale
staleLabel: stale
# Limit to only `issues` or `pulls`
only: issues
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. However, it might still be relevant so please leave a short comment if it should remain open. Otherwise the issue will be closed automatically after two weeks. Thank you
    for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
    This issue has been automatically closed because no further activity occurred. If you think this issue is still relevant please reopen it or contact @dsilhavy. Thank you
    for your contributions.
    