name: 'Setup dash.js'
description: 'Setup Node.js, cache and install dependencies'

runs:
    using: 'composite'
    steps:
        -   name: Setup Node.js
            uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
            with:
                node-version: '20'
                cache: 'npm'
        -   name: Cache node modules
            id: cache-npm
            uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
            with:
                path: node_modules
                key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
        -   name: Install dependencies
            if: steps.cache-npm.outputs.cache-hit != 'true'
            shell: bash
            run: npm install
