name: deploy

on:
    workflow_call:
        inputs:
            envname:
                required: true
                type: string
            deploy_path:
                required: true
                type: string
        secrets:
            host:
                required: true
            user:
                required: true
            private_key:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: "14.x"
            -   name: Install dependencies
                run: npm install
            -   name: Run build
                run: npm run build
    deploy:
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            -   name: Copy to staging directory for deployment
                run: |
                    mkdir deploy
                    cp contrib dist samples test/function/tests.html test/functional/testsCommon.js test/functional/testCommon.js test/functional/config test/functional/tests/ ./deploy/ 

            -   name: deploy file to server
                uses: wlixcc/SFTP-Deploy-Action@v1.2.4
                with:
                    username: ${{ secrets.user }}
                    server: ${{ secrets.host }}
                    ssh_private_key: ${{ secrets.private_key }}
                    local_path: './deploy'
                    remote_path: ${{inputs.deploy_path}}