name: deploy_v5

on:
    push:
        branches:
            - 'v5.0.0'

jobs:
    deploy_staging:
        if: github.repository == 'Dash-Industry-Forum/dash.js'
        uses: ./.github/workflows/deploy.yml
        with:
            envname: v5
            deploy_path: '/377335/dash.js'
        secrets:
            host: ${{secrets.HOST}}
            user: ${{secrets.USER}}
            private_key: ${{secrets.PRIVATE_KEY}}
