name: deploy_latest_as_version_folder

on:
    push:
        branches:
            - 'feature/ciDeployment'

jobs:
    get_version_number:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.set_version.outputs.version }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Read version from package.json
              id: set_version
              run: |
                  echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
              shell: bash

            - name: Print version
              run: |
                  echo "Version: ${{ steps.set_version.outputs.version }}"

    deploy:
        needs: get_version_number
        uses: ./.github/workflows/deploy.yml
        with:
            envname: ${{ needs.get_version_number.outputs.version }}-test-dsi
            deploy_path: '/377335/dash.js'
        secrets:
            host: ${{ secrets.HOST }}
            user: ${{ secrets.USER }}
            private_key: ${{ secrets.PRIVATE_KEY }}